//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoormatWebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoormatWebSite.Resources.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tax.
        /// </summary>
        public static string ArzeshAfzodeh {
            get {
                return ResourceManager.GetString("ArzeshAfzodeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Discription.
        /// </summary>
        public static string AttachmentDiscription {
            get {
                return ResourceManager.GetString("AttachmentDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Phone.
        /// </summary>
        public static string CustomerPhone {
            get {
                return ResourceManager.GetString("CustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discription.
        /// </summary>
        public static string discription {
            get {
                return ResourceManager.GetString("discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Discription.
        /// </summary>
        public static string FactorDiscription {
            get {
                return ResourceManager.GetString("FactorDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor State.
        /// </summary>
        public static string FactorStateID {
            get {
                return ResourceManager.GetString("FactorStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Title.
        /// </summary>
        public static string FactorStateTitle {
            get {
                return ResourceManager.GetString("FactorStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Attach.
        /// </summary>
        public static string FileAttach {
            get {
                return ResourceManager.GetString("FileAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Gallery .
        /// </summary>
        public static string GalleryImage {
            get {
                return ResourceManager.GetString("GalleryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string GalleryName {
            get {
                return ResourceManager.GetString("GalleryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        public static string idSize {
            get {
                return ResourceManager.GetString("idSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Words.
        /// </summary>
        public static string KeyWord {
            get {
                return ResourceManager.GetString("KeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Code.
        /// </summary>
        public static string LanguageTypeTitle {
            get {
                return ResourceManager.GetString("LanguageTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service Image.
        /// </summary>
        public static string ourserviceimage {
            get {
                return ResourceManager.GetString("ourserviceimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service Subtitle.
        /// </summary>
        public static string ourserviceSubtitle {
            get {
                return ResourceManager.GetString("ourserviceSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service Title.
        /// </summary>
        public static string ourserviceTitle {
            get {
                return ResourceManager.GetString("ourserviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service Url.
        /// </summary>
        public static string ourserviceUrl {
            get {
                return ResourceManager.GetString("ourserviceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Type.
        /// </summary>
        public static string OurWorkGalleryTypeId {
            get {
                return ResourceManager.GetString("OurWorkGalleryTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Type Title.
        /// </summary>
        public static string OurWorkGalleryTypeTitle {
            get {
                return ResourceManager.GetString("OurWorkGalleryTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Address.
        /// </summary>
        public static string PartnerAddress {
            get {
                return ResourceManager.GetString("PartnerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner City.
        /// </summary>
        public static string PartnerCity {
            get {
                return ResourceManager.GetString("PartnerCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Mobile.
        /// </summary>
        public static string PartnerMobile {
            get {
                return ResourceManager.GetString("PartnerMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Number 1 .
        /// </summary>
        public static string PartnerNumber {
            get {
                return ResourceManager.GetString("PartnerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Number 2 .
        /// </summary>
        public static string PartnerNumber1 {
            get {
                return ResourceManager.GetString("PartnerNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string PartnerSelectLanguage {
            get {
                return ResourceManager.GetString("PartnerSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Title.
        /// </summary>
        public static string PartnerTitle {
            get {
                return ResourceManager.GetString("PartnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon.
        /// </summary>
        public static string planicon {
            get {
                return ResourceManager.GetString("planicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Date.
        /// </summary>
        public static string PostDate {
            get {
                return ResourceManager.GetString("PostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Short Discription.
        /// </summary>
        public static string PostShortDiscription {
            get {
                return ResourceManager.GetString("PostShortDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Text.
        /// </summary>
        public static string PostText {
            get {
                return ResourceManager.GetString("PostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string PostTitle {
            get {
                return ResourceManager.GetString("PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Type.
        /// </summary>
        public static string PostType {
            get {
                return ResourceManager.GetString("PostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Type Title.
        /// </summary>
        public static string PostTypeTitle {
            get {
                return ResourceManager.GetString("PostTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Posted.
        /// </summary>
        public static string PostUser {
            get {
                return ResourceManager.GetString("PostUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Date Create.
        /// </summary>
        public static string ProductDateCreate {
            get {
                return ResourceManager.GetString("ProductDateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ProductGalleryImage {
            get {
                return ResourceManager.GetString("ProductGalleryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Gallery Title.
        /// </summary>
        public static string ProductGalleryTitle {
            get {
                return ResourceManager.GetString("ProductGalleryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product KeyWords.
        /// </summary>
        public static string ProductKeyWord {
            get {
                return ResourceManager.GetString("ProductKeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Pic Thumbnail.
        /// </summary>
        public static string ProductPicThumbnail {
            get {
                return ResourceManager.GetString("ProductPicThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discription.
        /// </summary>
        public static string ProductPropertyDiscription {
            get {
                return ResourceManager.GetString("ProductPropertyDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Title.
        /// </summary>
        public static string ProductPropertyTitle {
            get {
                return ResourceManager.GetString("ProductPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Short Discription.
        /// </summary>
        public static string ProductShortDiscription {
            get {
                return ResourceManager.GetString("ProductShortDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductText.
        /// </summary>
        public static string ProductText {
            get {
                return ResourceManager.GetString("ProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Title.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Product Type.
        /// </summary>
        public static string ProductTypeSelected {
            get {
                return ResourceManager.GetString("ProductTypeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type Title.
        /// </summary>
        public static string ProductTypeTitle {
            get {
                return ResourceManager.GetString("ProductTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Unit Salary.
        /// </summary>
        public static string ProductUnitSalary {
            get {
                return ResourceManager.GetString("ProductUnitSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Product Unite.
        /// </summary>
        public static string ProductUnitType {
            get {
                return ResourceManager.GetString("ProductUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please inter {0}.
        /// </summary>
        public static string Requaried {
            get {
                return ResourceManager.GetString("Requaried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string RowFactorAmount {
            get {
                return ResourceManager.GetString("RowFactorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string RowFactorCount {
            get {
                return ResourceManager.GetString("RowFactorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discription.
        /// </summary>
        public static string RowFactorDiscription {
            get {
                return ResourceManager.GetString("RowFactorDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor Number.
        /// </summary>
        public static string RowFactorFactor {
            get {
                return ResourceManager.GetString("RowFactorFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght.
        /// </summary>
        public static string RowFactorLenght {
            get {
                return ResourceManager.GetString("RowFactorLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string RowFactorProduct {
            get {
                return ResourceManager.GetString("RowFactorProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string RowFactorSalary {
            get {
                return ResourceManager.GetString("RowFactorSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string RowFactorWidth {
            get {
                return ResourceManager.GetString("RowFactorWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Salary.
        /// </summary>
        public static string ServiceSalary {
            get {
                return ResourceManager.GetString("ServiceSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Title.
        /// </summary>
        public static string ServiceTitle {
            get {
                return ResourceManager.GetString("ServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Image.
        /// </summary>
        public static string SliderImage {
            get {
                return ResourceManager.GetString("SliderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Subtitle .
        /// </summary>
        public static string SliderSubtitle {
            get {
                return ResourceManager.GetString("SliderSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Text.
        /// </summary>
        public static string SliderSubtitle2 {
            get {
                return ResourceManager.GetString("SliderSubtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string SliderSubtitle3 {
            get {
                return ResourceManager.GetString("SliderSubtitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Title.
        /// </summary>
        public static string SliderTitle {
            get {
                return ResourceManager.GetString("SliderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Salary.
        /// </summary>
        public static string TotalSalary {
            get {
                return ResourceManager.GetString("TotalSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string UnitTypeTitle {
            get {
                return ResourceManager.GetString("UnitTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Factor Create.
        /// </summary>
        public static string UserFactor {
            get {
                return ResourceManager.GetString("UserFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Product Create.
        /// </summary>
        public static string UserProduct {
            get {
                return ResourceManager.GetString("UserProduct", resourceCulture);
            }
        }
    }
}
