//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoormatWebSite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoormatWebSite.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No49, GolPar Alley , Motahari st , Emamzadeh Blv , Qods City , Tehran , Iran.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazing Projects.
        /// </summary>
        public static string AmazingProjects {
            get {
                return ResourceManager.GetString("AmazingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doormat.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backery products.
        /// </summary>
        public static string BackeryProducts {
            get {
                return ResourceManager.GetString("BackeryProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.
        /// </summary>
        public static string BackeryProductsNumber {
            get {
                return ResourceManager.GetString("BackeryProductsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string BackeryProductsSubTitle {
            get {
                return ResourceManager.GetString("BackeryProductsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call us anytime.
        /// </summary>
        public static string Callusanytime {
            get {
                return ResourceManager.GetString("Callusanytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT US.
        /// </summary>
        public static string CONTACTUS {
            get {
                return ResourceManager.GetString("CONTACTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Blog Website.
        /// </summary>
        public static string FromBlogWebsite {
            get {
                return ResourceManager.GetString("FromBlogWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get In Touch.
        /// </summary>
        public static string GetInTouch {
            get {
                return ResourceManager.GetString("GetInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy clients.
        /// </summary>
        public static string Happyclients {
            get {
                return ResourceManager.GetString("Happyclients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5440.
        /// </summary>
        public static string HappyclientsNumber {
            get {
                return ResourceManager.GetString("HappyclientsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every week.
        /// </summary>
        public static string HappyclientsSubtitle {
            get {
                return ResourceManager.GetString("HappyclientsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please send file .
        /// </summary>
        public static string interfile {
            get {
                return ResourceManager.GetString("interfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter valid mail.
        /// </summary>
        public static string intermail {
            get {
                return ResourceManager.GetString("intermail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter valid text.
        /// </summary>
        public static string intertext {
            get {
                return ResourceManager.GetString("intertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Work Time.
        /// </summary>
        public static string InWorkTime {
            get {
                return ResourceManager.GetString("InWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATEST Post.
        /// </summary>
        public static string LATESTPost {
            get {
                return ResourceManager.GetString("LATESTPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Posts.
        /// </summary>
        public static string LatestPosts {
            get {
                return ResourceManager.GetString("LatestPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login on site.
        /// </summary>
        public static string Loginonsite {
            get {
                return ResourceManager.GetString("Loginonsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti Slips.
        /// </summary>
        public static string menuAntiSlips {
            get {
                return ResourceManager.GetString("menuAntiSlips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string menuBlog {
            get {
                return ResourceManager.GetString("menuBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string menuContactUS {
            get {
                return ResourceManager.GetString("menuContactUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matts.
        /// </summary>
        public static string MenuMatts {
            get {
                return ResourceManager.GetString("MenuMatts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Products.
        /// </summary>
        public static string menuOtherProducts {
            get {
                return ResourceManager.GetString("menuOtherProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking Pakage.
        /// </summary>
        public static string menuParkingPakage {
            get {
                return ResourceManager.GetString("menuParkingPakage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string MenuProducts {
            get {
                return ResourceManager.GetString("MenuProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Services.
        /// </summary>
        public static string MoreServices {
            get {
                return ResourceManager.GetString("MoreServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next&gt;.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donec sed odio dui. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donecullamcorper nulla non metus auctor fringilla..
        /// </summary>
        public static string ourServiceDiscription {
            get {
                return ResourceManager.GetString("ourServiceDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR SERVICES.
        /// </summary>
        public static string OURSERVICES {
            get {
                return ResourceManager.GetString("OURSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner stores.
        /// </summary>
        public static string Partnerstores {
            get {
                return ResourceManager.GetString("Partnerstores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        public static string PartnerstoresNumber {
            get {
                return ResourceManager.GetString("PartnerstoresNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the whole state.
        /// </summary>
        public static string PartnerstoresSubTitle {
            get {
                return ResourceManager.GetString("PartnerstoresSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +(98)2146891581.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PURCHASE NOW.
        /// </summary>
        public static string PURCHASENOW {
            get {
                return ResourceManager.GetString("PURCHASENOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha.
        /// </summary>
        public static string Recaptcha {
            get {
                return ResourceManager.GetString("Recaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; All Rights Reserved.
        /// </summary>
        public static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your keywords....
        /// </summary>
        public static string SearchPlaceHolder {
            get {
                return ResourceManager.GetString("SearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE :.
        /// </summary>
        public static string SHARE {
            get {
                return ResourceManager.GetString("SHARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donec sed odio dui. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla..
        /// </summary>
        public static string SloganDiscription {
            get {
                return ResourceManager.GetString("SloganDiscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doormat first choice of customers.
        /// </summary>
        public static string sloganTitle {
            get {
                return ResourceManager.GetString("sloganTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT NOW.
        /// </summary>
        public static string SUBMITNOW {
            get {
                return ResourceManager.GetString("SUBMITNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAGS :.
        /// </summary>
        public static string TAGS {
            get {
                return ResourceManager.GetString("TAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday to Thursday from 8:00 to 17:00.
        /// </summary>
        public static string TimeWork {
            get {
                return ResourceManager.GetString("TimeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras aliquam sagittis ex, ac finibus lectus lacinia a. Mauris non ligula nec libero finibus blandit. Vestibulum volutpat sagittis dolor nec euismod. Vivamus in scelerisque elit. Donec odio orci, placerat non leo ac, mollis pellentesque est. Etiam sit amet imperdiet tellus..
        /// </summary>
        public static string VideoWarpText {
            get {
                return ResourceManager.GetString("VideoWarpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check &lt;i class=&quot;theme-clr&quot;&gt;Video Presentation to&lt;/i&gt; find out More About us.
        /// </summary>
        public static string VideoWarpTitle {
            get {
                return ResourceManager.GetString("VideoWarpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What We Do For You.
        /// </summary>
        public static string WhatWeDoForYou {
            get {
                return ResourceManager.GetString("WhatWeDoForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours:.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year experience.
        /// </summary>
        public static string Yearexperience {
            get {
                return ResourceManager.GetString("Yearexperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string YearexperienceNumber {
            get {
                return ResourceManager.GetString("YearexperienceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted manufacturer.
        /// </summary>
        public static string YearexperienceSubTitle {
            get {
                return ResourceManager.GetString("YearexperienceSubTitle", resourceCulture);
            }
        }
    }
}
