//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentFactor
    {
        public int AttachmentFactorID { get; set; }
        public string AttachmentDiscription { get; set; }
        public string FileAttach { get; set; }
        public Nullable<int> FactorID { get; set; }
    
        public virtual Factor Factor { get; set; }
    }
}
