//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoormatWebSiteEntities1 : DbContext
    {
        public DoormatWebSiteEntities1()
            : base("name=DoormatWebSiteEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AttachmentFactor> AttachmentFactor { get; set; }
        public virtual DbSet<Factor> Factor { get; set; }
        public virtual DbSet<FactorAndService> FactorAndService { get; set; }
        public virtual DbSet<FactorState> FactorState { get; set; }
        public virtual DbSet<languageType> languageType { get; set; }
        public virtual DbSet<OurWorkGallery> OurWorkGallery { get; set; }
        public virtual DbSet<OurWorkGalleryType> OurWorkGalleryType { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostType> PostType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductGallery> ProductGallery { get; set; }
        public virtual DbSet<ProductProperty> ProductProperty { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<RowFactor> RowFactor { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<UnitType> UnitType { get; set; }
    }
}
