//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorAndService
    {
        public int id { get; set; }
        public int ServiceID { get; set; }
        public int FactorID { get; set; }
    
        public virtual Factor Factor { get; set; }
        public virtual Service Service { get; set; }
    }
}
