//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factor()
        {
            this.AttachmentFactor = new HashSet<AttachmentFactor>();
            this.FactorAndService = new HashSet<FactorAndService>();
            this.RowFactor = new HashSet<RowFactor>();
        }
    
        public int FactorID { get; set; }
        public string AspNetUserID { get; set; }
        public double TotalSalary { get; set; }
        public Nullable<int> Discount { get; set; }
        public System.DateTime Date { get; set; }
        public int FactorStateID { get; set; }
        public string FactorDiscription { get; set; }
        public double Salary { get; set; }
        public Nullable<double> ArzeshAfzodeh { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerAddress { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttachmentFactor> AttachmentFactor { get; set; }
        public virtual FactorState FactorState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactorAndService> FactorAndService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RowFactor> RowFactor { get; set; }
    }
}
