//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurWorkGallery
    {
        public int id { get; set; }
        public int OurWorkGalleryTypeId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    
        public virtual OurWorkGalleryType OurWorkGalleryType { get; set; }
    }
}
