//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PhoneNumer { get; set; }
        public string PhoneNumer2 { get; set; }
        public string Mobile { get; set; }
        public int languageType { get; set; }
    
        public virtual languageType languageType1 { get; set; }
    }
}
