//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostID { get; set; }
        [Required]
        [Display(Name = "Title",ResourceType = typeof())]
        public string PostTitle { get; set; }
        public string PostText { get; set; }
        public Nullable<int> PostTypeID { get; set; }
        public string PostShortDiscription { get; set; }
        public System.DateTime PostDate { get; set; }
        public string KeyWord { get; set; }
        public string AspNetUsersID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual PostType PostType { get; set; }
    }
}
