//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductGallery = new HashSet<ProductGallery>();
            this.ProductProperty = new HashSet<ProductProperty>();
            this.RowFactor = new HashSet<RowFactor>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string AspNetUserID { get; set; }
        public string Title { get; set; }
        public string ShortDiscription { get; set; }
        public string Text { get; set; }
        public string PicThumbnail { get; set; }
        public string KeyWord { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> UnitSalary { get; set; }
        public int UnitID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual UnitType UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGallery> ProductGallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductProperty> ProductProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RowFactor> RowFactor { get; set; }
    }
}
