//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RowFactor
    {
        public int RowFactorID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> FactorID { get; set; }
        public Nullable<double> Lenght { get; set; }
        public Nullable<double> Width { get; set; }
        public int Count { get; set; }
        public double Amount { get; set; }
        public double RowSalary { get; set; }
        public string RowDiscription { get; set; }
    
        public virtual Factor Factor { get; set; }
        public virtual Product Product { get; set; }
    }
}
