//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoormatWebSite.Areas.Admin.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoormatWebSite.Areas.Admin.Resource.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backgrand.
        /// </summary>
        public static string backgrand {
            get {
                return ResourceManager.GetString("backgrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BacktoList {
            get {
                return ResourceManager.GetString("BacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butten URL.
        /// </summary>
        public static string buttenURL {
            get {
                return ResourceManager.GetString("buttenURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string Choosefile {
            get {
                return ResourceManager.GetString("Choosefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Slider.
        /// </summary>
        public static string CreateSlider {
            get {
                return ResourceManager.GetString("CreateSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string DirectionSetting {
            get {
                return ResourceManager.GetString("DirectionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        public static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Slider.
        /// </summary>
        public static string EditSlider {
            get {
                return ResourceManager.GetString("EditSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please inter Your Butten URL.
        /// </summary>
        public static string interButtenURL {
            get {
                return ResourceManager.GetString("interButtenURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please inter Your URL for Butten Read More.
        /// </summary>
        public static string InterURL {
            get {
                return ResourceManager.GetString("InterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please inter Your video URL .
        /// </summary>
        public static string interURLVideo {
            get {
                return ResourceManager.GetString("interURLVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Choice File Video.
        /// </summary>
        public static string OrChoiceFileVideo {
            get {
                return ResourceManager.GetString("OrChoiceFileVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please inter {0} . {0} is required..
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoment Size 160*160.
        /// </summary>
        public static string SelectourclientsComment {
            get {
                return ResourceManager.GetString("SelectourclientsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoment Size 1920*892.
        /// </summary>
        public static string SelectSliderComment {
            get {
                return ResourceManager.GetString("SelectSliderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Setting.
        /// </summary>
        public static string SiteSetting {
            get {
                return ResourceManager.GetString("SiteSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Settings.
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Image.
        /// </summary>
        public static string videoWarpVideoImage {
            get {
                return ResourceManager.GetString("videoWarpVideoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this ? .
        /// </summary>
        public static string warningDelete {
            get {
                return ResourceManager.GetString("warningDelete", resourceCulture);
            }
        }
    }
}
